### PR TITLE
Widget refactor

### PR DESCRIPTION
**Pull request by AndresVidalBerriel**
#### :link: Trello board reference:

- [Refactor del loop de mensajes del widget](https://trello.com/c/0mcNUjcz)

---

#### :pencil2: Description:

The widget has been refactored due to the following reasons:

- Previous state management was inefficient, as every state was handled by top-level component `Widget`, causing unnecesary repeated renderization of the whole app.

- Message loss before connection is properly stablished (a chat id is assigned and the websocket is subscribed to the action cable channel) was prevented by disabling the input until the socket is ready. This compromises the usability of the app.

- Project structure was significantly different from it's dashboard counterpart, difficulting the coordination of the team and development standarization.

Changes introduced by this PR include:

- Encapsulation of API calls in a single ChatController class
- Configuration to use `redux` and project reorganization so it is used in a similar way to how it's used in the dashboard project
- Implementation of a message queue that ensures that messages are sent once and when the connection is stablished
- Separation of business logic from presentation in some components
- Connection status management

---

#### :pushpin: Notes:
**To Do (in this task, going to be included in a different PR):**
- Message delivery confirmation (both message received by the server and message broadcasted in channel)
- Associated with last item, error handling when message delivery is not acknowledged or not broadcasted back by the server

**To Do (may be out of scope for this task):**
- Separation between presentation and logic on the other components
- Enhance error handling

### CODE REVIEW

**Comment by agusit7** [comment]
As a team, we had decided to not include Redux on the widget. We suggested the use of the ContextAPI as Tinte mentioned. We thought redux was too much boilerplate for such a small component and would add unnecessary overhead to the development. What do you think about changing it?

**Comment by AndresVidalBerriel** [comment]
> I agree with Tinte suggestion to use ContextAPI. I think redux has too much boilerplate for such a small component and would add unnecessary overhead to the development. What do you think about changing it?

I did not understand that not using redux for this component was an explicit decision, that's totally my fault! Still, state handling turned out to be trickier than (at least I) expected and redux made possible some clean solutions. We should also consider that dashboard-side chats and widget chat share a lot of business logic. I'll do further research about Context API so I can give my feedback about this and change it as soon as possible if it is necessary!

**Comment by AndresVidalBerriel** [comment]
> @AndresVidalBerriel
> Is redux really necessary for the widget? What do you think about using the context api?

I misunderstood a team decision about this and rushed to study and use redux to solve the problemas I encountered during the refactor. I'll do further research about Context API and change it if it's necessary.

**Comment by agusit7** [comment]
@AndresVidalB Sorry If my first message sounded like it was the final decision. Not using redux was just something we proposed before writing a line of code, so we can change our minds if after doing some work we find that it's our best option! Let's investigate and discuss with the rest of the team what fits our needs the best.

**Pull request closed without merging**
